---
- name: Check if Vagrant is already installed
  command: "vagrant --version"
  register: test
  ignore_errors: yes
  failed_when: no
  changed_when: yes

- name: Installation block
  when: test.msg is defined or
    not (test.stdout | regex_search('^Vagrant ' + vagrant_version | string))
  block:

    - name: Set extension for Ubuntu
      when: ansible_distribution == 'Ubuntu'
      set_fact:
        vagrant_install_ext: deb

    - name: Set extension for CentOS
      when: ansible_distribution == 'CentOS'
      set_fact:
        vagrant_install_ext: rpm

    - name: Download the file
      get_url:
        url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_x86_64.{{ vagrant_install_ext }}"
        dest: "{{ vagrant_install_tmp }}.{{ vagrant_install_ext }}"

    - name: Install package (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      apt:
        deb: "{{ vagrant_install_tmp }}.{{ vagrant_install_ext }}"

    - name: Install package (CentOS)
      when: ansible_distribution == 'CentOS'
      yum:
        name: "{{ vagrant_install_tmp }}.{{ vagrant_install_ext }}"
